#!/usr/bin/env sh

if [ "$1" = "clean" ]; then
    rm -rf build/
fi

mkdir -p build/ &&
    latexmk -shell-escape -output-directory=build/ -xelatex &&
    zathura build/main.pdf &&
    (scp build/main.pdf server:/home/melvin/Abizeugs/zeitung.pdf &>/dev/null)
